version: 2.1
jobs:
  build_java:
    working_directory: ~/hello_world
    docker:
      - image: circleci/openjdk:13.0-buster # https://hub.docker.com/r/circleci/openjdk, 12 is not available
    steps:
      - checkout
      - restore_cache:
          key: hello_world-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: hello_world-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: java -classpath target/classes mcev.hello.HelloWorld
  build_javascript_and_perl:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: node src/main/js/hello_world.js
      - run: perl src/main/perl/hello_world.pl
  build_ruby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: ruby src/main/ruby/hello_world.rb
workflows:
  version: 2
  build_all:
    jobs:
      - build_java
      - build_javascript_and_perl
      - build_ruby
